/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form.pinjaman;

import form.Angsuran.tambah_angsuran;
//import java.beans.PropertyVetoException;
import java.sql.ResultSet;
//import java.util.logging.Level;
//import java.util.logging.Logger;
//import javax.swing.JDesktopPane;
import javax.swing.table.DefaultTableModel;
import module.pinjaman;

/**
 *
 * @author user
 */
public class cari_pinjaman extends javax.swing.JInternalFrame {

    /**
     * Creates new form cari_pinjaman
     */
    public cari_pinjaman() {
        initComponents();
    }
    
    public void showTable(ResultSet data){
        DefaultTableModel tabel_pinjaman = new DefaultTableModel();
        tabel_pinjaman.addColumn("NO.");
        tabel_pinjaman.addColumn("ID ANGGOTA");
        tabel_pinjaman.addColumn("LAMA PINJAMAN");
        tabel_pinjaman.addColumn("JUMLAH");
        tabel_pinjaman.addColumn("TANGGAL");
        //ResultSet data = anggota.getDataAnggota();
        try {
            while (data.next()) {            
                tabel_pinjaman.addRow(new Object[]{
                    data.getString("no"),
                    data.getString("id_anggota"),
                    data.getInt("lama_pinjaman"),
                    data.getInt("jumlah"),
                    data.getDate("tanggal").toString()
                });
                tabelPinjaman.setModel(tabel_pinjaman);
        }
        } catch (Exception e) {
            System.out.println(e.getLocalizedMessage().toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPinjaman = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cari Pinjaman");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setText("Cari Pinjaman");

        cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cariKeyReleased(evt);
            }
        });

        tabelPinjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NO", "ID ANGGOTA", "LAMA", "JUMLAH", "TANGGAL"
            }
        ));
        tabelPinjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPinjamanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPinjaman);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cari))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        showTable(pinjaman.data());
    }//GEN-LAST:event_formInternalFrameActivated

    private void cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariKeyReleased
        // TODO add your handling code here:
        showTable(pinjaman.cari(cari.getText()));
    }//GEN-LAST:event_cariKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        tambah_angsuran form = new tambah_angsuran();
        pinjaman.setNo(pinjaman.getNo());
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabelPinjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPinjamanMouseClicked
        // TODO add your handling code here:
        int x = tabelPinjaman.getSelectedRow();
        if (x != -1){
            pinjaman.setNo(tabelPinjaman.getValueAt(x,0).toString());
        }
    }//GEN-LAST:event_tabelPinjamanMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cari;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelPinjaman;
    // End of variables declaration//GEN-END:variables
}
